import { readFile, writeFile, mkdir, rm, cp } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const out = path.join(root, 'dist');
const data = JSON.parse(await readFile(path.join(root, 'data/portfolio.json'), 'utf8'));
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const categoryNames = {realestate:'Real estate',lifestyle:'Lifestyle',fashion:'Fashion & brands',recruitment:'Recruitment'};
const arrow = '<span aria-hidden="true">↗</span>';
const logo = '<img src="/assets/brand/logo-white.webp" width="700" height="390" alt="The Social Buzz">';
function header(active = '') {
  return `<a class="skip-link" href="#main">Skip to content</a><header class="nav"><a class="logo" href="/" aria-label="The Social Buzz home">${logo}</a><nav aria-label="Main navigation"><a href="/work/" ${active==='work'?'aria-current="page"':''}>The work</a><a href="/#services">What we do</a><a href="/#system">How we work</a><a href="/founder/" ${active==='founder'?'aria-current="page"':''}>The founder</a></nav><a class="btn btn-small" href="/#contact">Let’s talk ${arrow}</a><button class="menu-toggle" type="button" aria-label="Open menu" aria-expanded="false" aria-controls="mobile-menu"><span></span><span></span></button></header><nav class="mobile-menu" id="mobile-menu" aria-label="Mobile navigation" aria-hidden="true" inert><a href="/work/">The work</a><a href="/#services">What we do</a><a href="/#system">How we work</a><a href="/founder/">The founder</a><a href="/#contact">Let’s talk</a><small>DUBAI, UAE · THE SOCIAL BUZZ</small></nav>`;
}
function socials(items, cls='social-links') { return `<div class="${cls}">${items.map(x=>`<a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">${esc(x.label)} ${arrow}</a>`).join('')}</div>`; }
function footer() {
  return `<footer class="footer wrap"><div class="footer-main"><a class="logo footer-logo" href="/" aria-label="The Social Buzz home">${logo}</a><p>Creative thinking.<br>Considered production.<br>A stronger presence.</p><div class="footer-contact"><a href="mailto:${data.company.email}">${data.company.email}</a><a href="${data.founder.phoneHref}">${data.founder.phone}</a><span>Dubai, United Arab Emirates</span></div></div><div class="footer-bottom"><span>© ${new Date().getUTCFullYear()} The Social Buzz</span><div><a href="${data.company.instagram}" target="_blank" rel="noopener noreferrer">Instagram ${arrow}</a><a href="${data.company.linkedin}" target="_blank" rel="noopener noreferrer">LinkedIn ${arrow}</a><a href="/privacy">Privacy</a></div><span>${esc(data.company.websiteLabel)}</span></div></footer>`;
}
function viewer() { return `<dialog class="project-viewer" aria-labelledby="viewer-title"><button class="viewer-close" type="button" aria-label="Close project">×</button><div class="viewer-layout"><div class="viewer-media"><img id="viewer-image" alt=""><button class="viewer-play" type="button" hidden><span aria-hidden="true">▶</span> Play film</button></div><div class="viewer-copy"><p class="eyebrow" id="viewer-category"></p><h2 id="viewer-title"></h2><p id="viewer-description"></p><div class="viewer-credit"><span>From the portfolio of</span><a href="/founder/">Ammer Afaq</a></div><div class="viewer-roles" aria-label="Creative roles"></div><a class="btn viewer-original" target="_blank" rel="noopener noreferrer">Watch the original ${arrow}</a><a class="textlink" href="/#contact">Create something with us ${arrow}</a><div class="viewer-controls"><button type="button" class="viewer-prev" aria-label="Previous project">←</button><span class="viewer-count"></span><button type="button" class="viewer-next" aria-label="Next project">→</button></div></div></div></dialog>`; }
function workCard(p, extra='') {
 return `<article class="work-card ${p.format==='film'?'work-card-film':'work-card-reel'} ${extra}" data-id="${p.id}" data-category="${p.category}" data-format="${p.format}"><div class="work-image"><button type="button" class="project-open" data-project="${p.id}" aria-label="View ${esc(p.title)}" aria-haspopup="dialog"><img src="${p.image}" ${p.thumbnailUrl?`data-thumbnail="${p.thumbnailUrl}"`:""} alt="${esc(p.title)} — portfolio preview" width="${p.width}" height="${p.height}" loading="lazy" decoding="async"><span class="project-play" aria-hidden="true">${p.url?'▶':'+'}</span><span class="project-index" aria-hidden="true">${p.id.split('-')[1]}</span></button><span class="format-tag">${p.url?(p.format==='film'?'FILM':'REEL'):'STILL'}</span></div><div class="work-caption"><div><p>${categoryNames[p.category]}</p><h3>${esc(p.title)}</h3></div>${p.url?`<a class="source-link" href="${esc(p.url)}" target="_blank" rel="noopener noreferrer" aria-label="Watch ${esc(p.title)} on ${p.platform}">${arrow}</a>`:'<span class="still-label">Portfolio still</span>'}</div></article>`;
}
function pressCards() {return data.press.map(p=>`<a class="press-card" href="${esc(p.url)}" target="_blank" rel="noopener noreferrer"><div class="press-image"><img src="${p.image}" alt="${esc(p.publisher)} feature from Ammer Afaq’s portfolio" width="${p.width}" height="${p.height}" loading="lazy" decoding="async"></div><div class="press-copy"><span class="eyebrow">${esc(p.publisher)}</span><h3>${esc(p.title)}</h3><p>${esc(p.description)}</p><span class="textlink">${p.id==='lovin-abu-dhabi'?'Watch the feature':'Read the story'} ${arrow}</span></div></a>`).join('');}
const selected = ['work-02','work-22','work-25','work-04','work-17','work-24'];
const tokens = {
 CREATIVE_STAGE: await readFile(path.join(root,'src/creative-stage.html'),'utf8'),
 FEATURED_WORK: selected.map(id=>workCard(data.projects.find(p=>p.id===id))).join(''),
 FILM_WORK: data.projects.filter(p=>p.format==='film').map(p=>workCard(p)).join(''),
 REEL_WORK: data.projects.filter(p=>p.format==='reel').map(p=>workCard(p)).join(''),
 FOUNDER_SOCIALS: socials(data.founder.socials),
 PRESS_CARDS: pressCards(),
 CONTACT_LINKS: `<a href="mailto:${data.company.email}">${data.company.email} ${arrow}</a><a href="${data.founder.phoneHref}">${data.founder.phone} ${arrow}</a>`,
 COMPANY_SOCIALS: socials([{label:'Instagram',url:data.company.instagram},{label:'LinkedIn',url:data.company.linkedin}]),
 FOOTER: footer(),VIEWER: viewer()
};
const pages=[{file:'home',route:'',title:'The Social Buzz — Creative Direction & Content Production, Dubai',description:'Founder-led creative direction, filmmaking and social content in Dubai. Explore real estate films, fashion, lifestyle and brand work by Ammer Afaq.'},{file:'work',route:'work',title:'The Work — Films & Reels by Ammer Afaq | The Social Buzz',description:'Explore 27 portfolio pieces across real estate, luxury, fashion, lifestyle and recruitment. Watch the original films and reels from Ammer Afaq’s portfolio.'},{file:'founder',route:'founder',title:'Ammer Afaq — Founder & Filmmaker | The Social Buzz',description:'Meet Ammer Afaq, filmmaker and founder of The Social Buzz. Explore his experience, skills, creative work and features in Khaleej Times, UAE Stories and Lovin Abu Dhabi.'}];
await rm(out,{recursive:true,force:true});await mkdir(out,{recursive:true});
await cp(path.join(root,'assets'),path.join(out,'assets'),{recursive:true});
for(const file of ['styles.css','script.js','motion.css','motion.js','privacy.html','success.html','404.html','site.webmanifest'])await cp(path.join(root,file),path.join(out,file));
await writeFile(path.join(out,'portfolio.json'),JSON.stringify(data));
for(const page of pages){
 let content=await readFile(path.join(root,'src',page.file+'.html'),'utf8');
 const all={...tokens,HEADER:header(page.route)};
 content=content.replace(/\{\{([A-Z_]+)\}\}/g,(_,key)=>{if(!(key in all))throw new Error('Unknown template '+key);return all[key]});
 const url='https://socialbuzzuae.com/'+(page.route?page.route+'/':'');
 const schema=page.route==='founder'?{'@context':'https://schema.org','@type':'Person',name:'Ammer Afaq',jobTitle:'Founder & Creative Marketing Strategist',url,email:data.founder.email,telephone:'+971501787917',sameAs:data.founder.socials.map(s=>s.url)}:{'@context':'https://schema.org','@type':page.route==='work'?'CollectionPage':'ProfessionalService',name:page.route==='work'?'The Social Buzz — Selected Work':'The Social Buzz',url,description:page.description,...(!page.route?{email:data.company.email,telephone:'+971501787917',areaServed:'Dubai, United Arab Emirates',founder:{'@type':'Person',name:'Ammer Afaq'}}:{})};
 const html=`<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#070910"><meta name="description" content="${esc(page.description)}"><title>${esc(page.title)}</title><link rel="canonical" href="${url}"><link rel="icon" href="/assets/brand/favicon.png" type="image/png"><link rel="manifest" href="/site.webmanifest"><meta property="og:type" content="website"><meta property="og:title" content="${esc(page.title)}"><meta property="og:description" content="${esc(page.description)}"><meta property="og:url" content="${url}"><meta property="og:image" content="https://socialbuzzuae.com/assets/brand/brand-gradient.webp"><meta name="twitter:card" content="summary_large_image"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Libre+Franklin:wght@400;500;600;700;800&family=Montserrat:wght@500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/motion.css"><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script></head><body class="page-${page.file}">${content}<script type="application/json" id="portfolio-data">${JSON.stringify(data.projects).replace(/</g,'\\u003c')}</script><script src="/script.js" defer></script><script src="/motion.js" defer></script></body></html>`;
 const directory=path.join(out,page.route);await mkdir(directory,{recursive:true});await writeFile(path.join(directory,'index.html'),html);
}
await writeFile(path.join(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['/','/work/','/founder/','/privacy'].map(route=>`<url><loc>https://socialbuzzuae.com${route}</loc></url>`).join('')}</urlset>`);
await writeFile(path.join(out,'robots.txt'),'User-agent: *\nAllow: /\nSitemap: https://socialbuzzuae.com/sitemap.xml\n');
console.log(`Built ${pages.length+3} pages, ${data.projects.length} projects and ${data.press.length} press features. No external build dependencies.`);
